OBJS = main.cpp logger.cpp textbox.cpp playerentity.cpp utilities.cpp projectile.cpp monster.cpp

OBJ_NAME = peup.out

all : $(OBJS)
	g++ $(OBJS) -Wall -std=c++17 -lSDL2 -lSDL2_image -lSDL2_ttf -o $(OBJ_NAME)
